### ISSUE TITLE
pear.phpunit.de doesn't exist anymore

### ISSUE THREAD

**Issue by rb2k** [escapestudios-cookbooks/phploc#3]
Just a heads up: The default install method (pear) will try to discover pear.phpunit.de (which doesn't exist anymore)

**Comment by djoos** [comment]
Hi @rb2k,

I've just released version 2.0.0 of the phploc cookbook, where the pear install method is removed. I've also updated the phar url and made some other end of year updates...

Thanks for getting in touch - hope this helps!

Kind regards,
David
